# Docker Compose for local testing before Coolify deployment
# Use: docker-compose up --build

version: '3.8'

services:
  flutter-flight-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    
    container_name: flight-compensation-app
    
    ports:
      - "8080:80"
    
    environment:
      - FLUTTER_ENV=production
      - FLUTTER_APP_NAME=Flight Compensation
      - FLUTTER_APP_VERSION=1.0.0
      - WEB_RENDERER=canvaskit
      - TREE_SHAKE_ICONS=true
      # Add your Supabase credentials here for local testing
      # - SUPABASE_URL=https://your-project-ref.supabase.co
      # - SUPABASE_ANON_KEY=your-anon-key
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits for local testing
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flight-app.rule=Host(\`localhost\`)"
      - "traefik.http.services.flight-app.loadbalancer.server.port=80"

networks:
  default:
    name: flight-app-network